Moved actionbarsherlock back to be a lib project because of this bug: http://stackoverflow.com/questions/11443262/actionbarsherlock-java-lang-noclassdeffounderror-com-actionbarsherlock-rstyle